name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./book/pom.xml
          mvn clean package -f ./writer/pom.xml
          mvn clean package -f ./user/pom.xml
          mvn clean package -f ./subscription/pom.xml
          mvn clean package -f ./bestseller/pom.xml
          mvn clean package -f ./openai/pom.xml
          mvn clean package -f ./point/pom.xml

      - name: Docker Build and push for Book
        uses: docker/build-push-action@v4
        with:
          context: ./book
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/book:latest
            ghcr.io/${{ github.repository }}/book:${{ github.ref_name }}
            
      - name: Docker Build and push for Writer
        uses: docker/build-push-action@v4
        with:
          context: ./writer
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/writer:latest
            ghcr.io/${{ github.repository }}/writer:${{ github.ref_name }}
            
      - name: Docker Build and push for User
        uses: docker/build-push-action@v4
        with:
          context: ./user
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/user:latest
            ghcr.io/${{ github.repository }}/user:${{ github.ref_name }}
            
      - name: Docker Build and push for Subscription
        uses: docker/build-push-action@v4
        with:
          context: ./subscription
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/subscription:latest
            ghcr.io/${{ github.repository }}/subscription:${{ github.ref_name }}
            
      - name: Docker Build and push for Bestseller
        uses: docker/build-push-action@v4
        with:
          context: ./bestseller
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/bestseller:latest
            ghcr.io/${{ github.repository }}/bestseller:${{ github.ref_name }}
            
      - name: Docker Build and push for Openai
        uses: docker/build-push-action@v4
        with:
          context: ./openai
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/openai:latest
            ghcr.io/${{ github.repository }}/openai:${{ github.ref_name }}
            
      - name: Docker Build and push for Point
        uses: docker/build-push-action@v4
        with:
          context: ./point
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/point:latest
            ghcr.io/${{ github.repository }}/point:${{ github.ref_name }}
            
